### ISSUE TITLE
Texture bugs on interaction cubes such as, crafting and bag. Also w/ the bags texture itself.

### ISSUE THREAD

**Issue by Lolsz312** [hammy3502/immersive-mc#291] opened 2023-08-29 21:17 UTC
This is just a bug i had on quest 1, vivecraft 1.16 virtual desktop. thank you for your time.

**Comment by hammy275** [comment] 2023-08-30 14:29
Please disable Optifine shaders to resolve this issue.

Duplicate of of https://github.com/hammy275/immersive-mc/issues/86 .

**Closed as not planned by hammy275** 2023-08-30 14:29 UTC
