### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by Koruzan** [hammy3502/immersive-mc#142] opened 2022-12-21 15:47 UTC
I put a stick into a crafting table and the game crashes.
i put something a chest the game crashes again.
and idk why but i cant get the backpack out might try again in a bit but still
it could be my pc but im not sure atm.

**Comment by hammy275** [comment] 2022-12-21 20:13
That seems really weird. What version of Minecraft are you using, are you on Forge or Fabric, and are you using any other mods? I've gotten a couple reports of modpacks having a tendency to cause issues.

If you can, please also send me the crash reports so I can look into what's happening, as this isn't reproducible on my end. Thanks!

**Comment by hammy275** [comment] 2023-01-05 14:05
Closing this due to inactivity. If something pops up again, please open a new issue. Thanks!

**Comment by Koruzan** [comment] 2023-01-05 15:36
only have the base mods that i need to use fabric version of the mod.

**Comment by Koruzan** [comment] 2023-01-05 15:36
and sorry for not replying was busy

**Comment by hammy275** [comment] 2023-01-05 15:36
All good! What versions of each mod are you using?

**Comment by Koruzan** [comment] 2023-01-05 16:15
1.19.2

**Comment by hammy275** [comment] 2023-01-05 16:45
What versions of each mod (Architectury, mc-vr-api, Forge Config API Port, ImmersiveMC) are you using?

And far more importantly, [**please send a crash log**](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report). It's effectively impossible to debug issues without one. Don't worry about deobfuscating it, I just need the first part of the link I attached (the "Obtaining the crash report file" part)

**Comment by hammy275** [comment] 2023-01-17 00:16
@Koruzan , any updates?

**Comment by Koruzan** [comment] 2023-01-17 15:37
nope
💀

**Comment by hammy275** [comment] 2023-01-17 16:10
Can you please follow the instructions in my comment a few up and send the mod versions and a crash log?

**Comment by hammy275** [comment] 2023-01-20 17:19
@Koruzan do you have the mod versions for all the mods you were using and **a crash log**? I can't make any progress without them

**Comment by hammy275** [comment] 2023-02-25 17:30
Closing due to inactvitiy. Sounds like you might have a really old mc-vr-api version, though.

**Closed as not planned by hammy275** 2023-02-25 17:30 UTC
Labels: bug
