### ISSUE TITLE
Incorrect display of numbers when shaders are enabled

### ISSUE THREAD

**Issue by Krypt0nC0R3** [hammy3502/immersive-mc#287] opened 2023-08-06 11:34 UTC
**Plugin version**: 1.4.0 Beta 1.1 (Forge)
**Game version**: 1.19.2
**Optifine version**: 1.19.2_HD_U_H9
**Forge version**: 43.2.21

Shaders with problems:

- BeyondBeliefLegacy_V1.2.2
- Chocapic13_HighPerformance_Low
- MakeUp-UltraFast-8.8e
- miniature-shader-2.0
- NobleRTv1.4.1
- PotatoShaders_v1.0d

**Proofs**

No shaders:
![2023-08-06_18 28 20](https://github.com/hammy275/immersive-mc/assets/46594859/e7441192-f5c2-48a2-8128-2273cc253843)

With any shader:
![2023-08-06_18 28 02](https://github.com/hammy275/immersive-mc/assets/46594859/67a2dea5-5844-4f4c-8990-afa153bb7891)

**Comment by hammy275** [comment] 2023-08-07 21:48
Thank you for the report! :)

This is an Optifine-compatibility bug I'm not planning to fix. I recommend switching Rubidium+Oculus (and switching to Mixin Vivecraft if you haven't already).

Closing as duplicate of https://github.com/hammy275/immersive-mc/issues/86

**Closed as not planned by hammy275** 2023-08-07 21:48 UTC
