### ISSUE TITLE
İts duplicating in 1.21.1

### ISSUE THREAD

**Issue by Umuteren31** [hammy3502/immersive-mc#474] opened 2024-09-21 08:21 UTC
When i try to craft a item its not comes to my hand i click to iron and its duplicates i have 5 iron and BONG i have seven its only in 1.21 pls fix it i love this mod or its maybe i didint dowload the vr api? #467 [](url)

**Comment by hammy275** [comment] 2024-09-21 18:30
MC VR API is purely to do with getting VR data to ImmersiveMC, it cannot interfere with anything related to items.

Can you please detail the _exact_ steps you are performing to get this? I attempted to re-create this from the limited information you provided, and could not re-create anything. Please also tell me which modloader you're using, in case if it's a modloader-specific issue, and any mods you have installed besides ImmersiveMC.

**Comment by hammy275** [comment] 2024-09-22 03:09
Got a similar report on Discord, so I can confirm this, crafting is quite buggy. For example, crafting a shield shows the output but won't let you grab it.

Reason seems to be because we pass vanilla the output slot when finding the recipe output, and it fails to get the recipe correctly when we do.

**Comment by hammy275** [comment] 2024-09-23 01:35
Fixed in ImmersiveMC 1.5.0 Beta 2.1

**Closed as completed by hammy275** 2024-09-23 01:35 UTC
Labels: bug
