### ISSUE TITLE
Recipies using item damaging or item replacement delete items

### ISSUE THREAD

**Issue by phoenixm77** [hammy3502/immersive-mc#479] opened 2024-10-06 11:45 UTC
recipes that damage an item in a craft delete the item instead of damaging the item same with items being replaced

**Comment by hammy275** [comment] 2024-10-06 13:47
This is known (duplicate of #219), and I will do my best to have fixed with ImmersiveMC 1.5.0.

**Closed as not planned by hammy275** 2024-10-06 13:47 UTC
