### ISSUE TITLE
Unable to Place Blocks onto BlockEntities While Sneaking

### ISSUE THREAD

**Issue by Mafuyu33** [hammy3502/immersive-mc#365] opened 2024-03-08 22:52 UTC
I found that when I'm sneaking (holding down the Shift key), I can't place blocks onto other block entities. For example, if I want to connect hoppers together, I can't do it easily.

**Comment by hammy275** [comment] 2024-03-08 23:16
Duplicate of https://github.com/hammy275/immersive-mc/issues/229 . Check there for how to solve this.

**Closed as not planned by hammy275** 2024-03-08 23:16 UTC

**Comment by Mafuyu33** [comment] 2024-03-08 23:20
My bad, I didn't check the previous issue.
