### ISSUE TITLE
Cobblemon Incompatibility

### ISSUE THREAD

**Issue by Jaec0b** [hammy3502/immersive-mc#502] opened 2024-11-27 08:22 UTC
Cobblemon Issue Page: https://gitlab.com/cable-mc/cobblemon/-/issues/1204

Summary:
The game is stuck on the saving world screen with Cobblemon when a Healing Factor has been rendered.

Steps to reproduce:
Install ImmersiveMC, Cobblemon and FabricAPI, open the game and create a world in creative, place down a Healing Machine, try to save and quit... the bug should then occur.

What is the current bug behavior?
The game gets stuck on the saving world screen.

What is the expected correct behavior?
The game saves and then quits to the title screen.

ImmersiveMC Version and Mod Loader:
ImmersiveMC 1.5.0-beta3, Minecraft Fabric 1.20.1
Also happens on 1.21.1

Mods used:
ImmersiveMC, Cobblemon, Fabric API

Relevant logs, screenshots and/or videos:
log: https://mclo.gs/T4DaxDv
log: https://mclo.gs/C6w9rpF no idea what this opengl error is the other time i got this bug
video: https://www.youtube.com/watch?v=5x2ypWTZMzA

**Comment by hammy275** [comment] 2024-11-27 14:22
Duplicate of #498. May post a temporarily fixed build on the ImmersiveMC Discord server soon if wanted.

**Closed as not planned by hammy275** 2024-11-27 14:22 UTC

**Comment by Jaec0b** [comment] 2024-11-28 13:52
> Duplicate of #498. May post a temporarily fixed build on the ImmersiveMC Discord server soon if wanted.

Awesome!, i cant wait to test it out.
